# Generated by Django 3.1.1 on 2020-09-14 10:25

from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import neksflis.payment.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=16, unique=True)),
                ('gateway', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('abc', 'abc'), ('xyz', 'xyz')], enum_class=neksflis.payment.enums.GatewayChoices, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=128)),
                ('raw_request', models.TextField()),
                ('raw_response', models.TextField()),
                ('is_succeeded', models.BooleanField()),
                ('transaction_type', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('token', 'token'), ('charge', 'charge')], enum_class=neksflis.payment.enums.TransactionType, max_length=32)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='payment.paymentoption')),
            ],
        ),
    ]
