# Generated by Django 3.1.1 on 2020-09-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription_period_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='subscription.subscriptionperioditem'),
        ),
        migrations.AlterUniqueTogether(
            name='paymenttransaction',
            unique_together={('transaction_id', 'payment_option')},
        ),
    ]
