# Generated by Django 3.1.1 on 2020-09-14 10:25

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import neksflis.subscription.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('active', 'active'), ('cancelled', 'cancelled')], default=neksflis.subscription.enums.SubscriptionStatus['ACTIVE'], enum_class=neksflis.subscription.enums.SubscriptionStatus, max_length=32)),
                ('plan', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('silver', 'silver'), ('gold', 'gold'), ('platinum', 'platinum')], enum_class=neksflis.subscription.enums.SubscriptionPlan, max_length=32)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('payment_data', models.JSONField(default=dict)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payment.paymentoption')),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': False, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPeriodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date_range', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('payment_status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('pending', 'pending'), ('completed', 'completed')], default=neksflis.subscription.enums.PaymentStatus['PENDING'], enum_class=neksflis.subscription.enums.PaymentStatus, max_length=32)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_period_items', to='subscription.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
